### ISSUE TITLE
Нет выделения

### ISSUE THREAD

**Issue by Ivan-Istomin** [VixusFoxy/VixTelegramThemes#1]
Нет цвета выделения как я понял

**Comment by Ivan-Istomin** [comment]
Ошибся, цвет выделения есть, просто он такой же как фон у сообщения собеседника, из-за этого не видно.

**Comment by Akyshnik** [comment]
Тоже заметил баг. Но можно определить выделение по цвету блока с временем отправки сообщения.

**Comment by Ivan-Istomin** [comment]
Сколько лет, сколько зим
