### ISSUE TITLE
Android/iOS Version?

### ISSUE THREAD

**Issue by BenHarksdorf** [VixusFoxy/VixTelegramThemes#3]
Would like to see a Android/iOS version of this one. I know there are ways to convert, but some might get lost there. So will there be one?

**Comment by VoodaGod** [comment]
check my fork, i've been porting this theme to android with some small tweaks
feel free to suggest changes

**Comment by austriker27** [comment]
@VoodaGod I know its been a few years, but I tried your fork and it didnt work. Would love to find a working 80s / synthwave android telegram theme!!

**Comment by austriker27** [comment]
@BenHarksdorf Did you ever find one for mobile phones?

**Comment by VixusFoxy** [comment]
> @BenHarksdorf Did you ever find one for mobile phones?

Hi! Send a message to @vixus on telegram and I'll sort you out with the Android version :)
@benharksdorf
@voodagod
@austriker27
